name: Build palen1x

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, aarch64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: echo "VERSION=2.0.2" >> $GITHUB_ENV

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static curl

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          sudo -E ./build.sh

      - name: Prepare artifact
        run: |
          mkdir palen1x
          cp work/*.iso palen1x/
          cp work/iso/boot/initramfs.xz palen1x/initramfs-${{ matrix.arch }}.xz
          echo "Prepared files in palen1x directory:"
          ls -l palen1x

      - name: Upload ISO to bashupload.com
        run: |
          ISO_FILE=$(find palen1x -name '*.iso' -print -quit)
          if [ -z "$ISO_FILE" ]; then
            echo "Error: ISO file not found in palen1x directory."
            exit 1
          fi
          echo "Uploading $ISO_FILE to bashupload.com..."
          curl --upload-file "$ISO_FILE" https://bashupload.com
